//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bio.Views.Alignment.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int SelectedFontSize {
            get {
                return ((int)(this["SelectedFontSize"]));
            }
            set {
                this["SelectedFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial")]
        public string SelectedFont {
            get {
                return ((string)(this["SelectedFont"]));
            }
            set {
                this["SelectedFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MinGroupingRange {
            get {
                return ((int)(this["MinGroupingRange"]));
            }
            set {
                this["MinGroupingRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRowNumbers {
            get {
                return ((bool)(this["ShowRowNumbers"]));
            }
            set {
                this["ShowRowNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>LightBlue</string>
  <string>LightCoral</string>
  <string>LightCyan</string>
  <string>LightGoldenrodYellow</string>
  <string>LightGray</string>
  <string>LightGreen</string>
  <string>LightPink</string>
  <string>LightSalmon</string>
  <string>LightSeaGreen</string>
  <string>LightSkyBlue</string>
  <string>LightSlateGray</string>
  <string>LightSteelBlue</string>
  <string>LightYellow</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ReferenceSequenceColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ReferenceSequenceColors"]));
            }
            set {
                this["ReferenceSequenceColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBlue")]
        public string SelectionColor {
            get {
                return ((string)(this["SelectionColor"]));
            }
            set {
                this["SelectionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string BackgroundColor {
            get {
                return ((string)(this["BackgroundColor"]));
            }
            set {
                this["BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string SelectionTextColor {
            get {
                return ((string)(this["SelectionTextColor"]));
            }
            set {
                this["SelectionTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBlue")]
        public string SeparatorColor {
            get {
                return ((string)(this["SeparatorColor"]));
            }
            set {
                this["SeparatorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBlue")]
        public string SelectionBorderColor {
            get {
                return ((string)(this["SelectionBorderColor"]));
            }
            set {
                this["SelectionBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string FocusedColor {
            get {
                return ((string)(this["FocusedColor"]));
            }
            set {
                this["FocusedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string FocusedBorderColor {
            get {
                return ((string)(this["FocusedBorderColor"]));
            }
            set {
                this["FocusedBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string ForegroundTextColor {
            get {
                return ((string)(this["ForegroundTextColor"]));
            }
            set {
                this["ForegroundTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGreen")]
        public string LineNumberTextColor {
            get {
                return ((string)(this["LineNumberTextColor"]));
            }
            set {
                this["LineNumberTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#30ff0000")]
        public string FocusRectColor {
            get {
                return ((string)(this["FocusRectColor"]));
            }
            set {
                this["FocusRectColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public string FocusRectBorderColor {
            get {
                return ((string)(this["FocusRectBorderColor"]));
            }
            set {
                this["FocusRectBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int AlignmentFontSize {
            get {
                return ((int)(this["AlignmentFontSize"]));
            }
            set {
                this["AlignmentFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas")]
        public string AlignmentFontFamily {
            get {
                return ((string)(this["AlignmentFontFamily"]));
            }
            set {
                this["AlignmentFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF363636")]
        public string GroupHeaderBackgroundColor {
            get {
                return ((string)(this["GroupHeaderBackgroundColor"]));
            }
            set {
                this["GroupHeaderBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string GroupHeaderTextColor {
            get {
                return ((string)(this["GroupHeaderTextColor"]));
            }
            set {
                this["GroupHeaderTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>AChocolate</string>
  <string>IIndianRed</string>
  <string>GDarkGreen</string>
  <string>UDeepPink</string>
  <string>CDarkBlue</string>
  <string>NDarkOliveGreen</string>
  <string>-LightGray</string>
  <string>~LightGray</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection NucleotideColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NucleotideColors"]));
            }
            set {
                this["NucleotideColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTaxonomyGroupLevel {
            get {
                return ((bool)(this["ShowTaxonomyGroupLevel"]));
            }
            set {
                this["ShowTaxonomyGroupLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SortByTaxonomy {
            get {
                return ((bool)(this["SortByTaxonomy"]));
            }
            set {
                this["SortByTaxonomy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenWithGrouping {
            get {
                return ((bool)(this["OpenWithGrouping"]));
            }
            set {
                this["OpenWithGrouping"] = value;
            }
        }
    }
}
