<?xml version="1.0" encoding="utf-8"?>
<Database Name="rCAD" Class="rcadDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=rCAD;Integrated Security=True" SettingsObjectName="Bio.Data.Providers.rCAD.RI.Properties.Settings" SettingsPropertyName="rCADConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Alignment" Member="Alignments">
    <Type Name="Alignment">
      <Column Name="AlnID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SeqTypeID" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AlignmentName" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="NextColumnNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vAlignmentGridUngapped" Member="vAlignmentGridUngappeds">
    <Type Name="vAlignmentGridUngapped">
      <Column Name="SeqID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AlnID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LogicalColumnNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BioSymbol" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="SequenceIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SequenceMain" Member="SequenceMains">
    <Type Name="SequenceMain">
      <Column Name="SeqID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaxID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocationID" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SeqTypeID" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SeqLength" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SequenceType" Member="SequenceTypes">
    <Type Name="SequenceType">
      <Column Name="SeqTypeID" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MoleculeType" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GeneType" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GeneName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CellLocationInfo" Member="CellLocationInfos">
    <Type Name="CellLocationInfo">
      <Column Name="LocationID" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Taxonomy" Member="Taxonomies">
    <Type Name="Taxonomy">
      <Column Name="TaxID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentTaxID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TaxonomyNamesOrdered" Member="TaxonomyNamesOrdereds">
    <Type Name="TaxonomyNamesOrdered">
      <Column Name="TaxID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ScientificName" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="LineageName" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>